/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangTermsRouteImport } from './routes/$lang/terms'
import { Route as LangPrivacyRouteImport } from './routes/$lang/privacy'
import { Route as LangEmailConfirmedRouteImport } from './routes/$lang/email-confirmed'
import { Route as LangDashboardRouteImport } from './routes/$lang/dashboard'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangAuthRouteImport } from './routes/$lang/auth'
import { Route as LangAdminRouteImport } from './routes/$lang/admin'
import { Route as ApiPublicVerifyKeyRouteImport } from './routes/api/public/verify-key'
import { Route as ApiPublicDeanonymizeRouteImport } from './routes/api/public/deanonymize'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicAnonymizeRouteImport } from './routes/api/public/anonymize'

const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangTermsRoute = LangTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangEmailConfirmedRoute = LangEmailConfirmedRouteImport.update({
  id: '/email-confirmed',
  path: '/email-confirmed',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangDashboardRoute = LangDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAuthRoute = LangAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAdminRoute = LangAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LangRouteRoute,
} as any)
const ApiPublicVerifyKeyRoute = ApiPublicVerifyKeyRouteImport.update({
  id: '/api/public/verify-key',
  path: '/api/public/verify-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeanonymizeRoute = ApiPublicDeanonymizeRouteImport.update({
  id: '/api/public/deanonymize',
  path: '/api/public/deanonymize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnonymizeRoute = ApiPublicAnonymizeRouteImport.update({
  id: '/api/public/anonymize',
  path: '/api/public/anonymize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/admin': typeof LangAdminRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/dashboard': typeof LangDashboardRoute
  '/$lang/email-confirmed': typeof LangEmailConfirmedRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/': typeof LangIndexRoute
  '/api/public/anonymize': typeof ApiPublicAnonymizeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/deanonymize': typeof ApiPublicDeanonymizeRoute
  '/api/public/verify-key': typeof ApiPublicVerifyKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/admin': typeof LangAdminRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/dashboard': typeof LangDashboardRoute
  '/$lang/email-confirmed': typeof LangEmailConfirmedRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang': typeof LangIndexRoute
  '/api/public/anonymize': typeof ApiPublicAnonymizeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/deanonymize': typeof ApiPublicDeanonymizeRoute
  '/api/public/verify-key': typeof ApiPublicVerifyKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/$lang/admin': typeof LangAdminRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/dashboard': typeof LangDashboardRoute
  '/$lang/email-confirmed': typeof LangEmailConfirmedRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/': typeof LangIndexRoute
  '/api/public/anonymize': typeof ApiPublicAnonymizeRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/deanonymize': typeof ApiPublicDeanonymizeRoute
  '/api/public/verify-key': typeof ApiPublicVerifyKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/auth'
    | '/$lang/contact'
    | '/$lang/dashboard'
    | '/$lang/email-confirmed'
    | '/$lang/privacy'
    | '/$lang/terms'
    | '/$lang/'
    | '/api/public/anonymize'
    | '/api/public/contact'
    | '/api/public/deanonymize'
    | '/api/public/verify-key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/admin'
    | '/$lang/auth'
    | '/$lang/contact'
    | '/$lang/dashboard'
    | '/$lang/email-confirmed'
    | '/$lang/privacy'
    | '/$lang/terms'
    | '/$lang'
    | '/api/public/anonymize'
    | '/api/public/contact'
    | '/api/public/deanonymize'
    | '/api/public/verify-key'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/auth'
    | '/$lang/contact'
    | '/$lang/dashboard'
    | '/$lang/email-confirmed'
    | '/$lang/privacy'
    | '/$lang/terms'
    | '/$lang/'
    | '/api/public/anonymize'
    | '/api/public/contact'
    | '/api/public/deanonymize'
    | '/api/public/verify-key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  ApiPublicAnonymizeRoute: typeof ApiPublicAnonymizeRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicDeanonymizeRoute: typeof ApiPublicDeanonymizeRoute
  ApiPublicVerifyKeyRoute: typeof ApiPublicVerifyKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/terms': {
      id: '/$lang/terms'
      path: '/terms'
      fullPath: '/$lang/terms'
      preLoaderRoute: typeof LangTermsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/email-confirmed': {
      id: '/$lang/email-confirmed'
      path: '/email-confirmed'
      fullPath: '/$lang/email-confirmed'
      preLoaderRoute: typeof LangEmailConfirmedRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/dashboard': {
      id: '/$lang/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangDashboardRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/auth': {
      id: '/$lang/auth'
      path: '/auth'
      fullPath: '/$lang/auth'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/admin': {
      id: '/$lang/admin'
      path: '/admin'
      fullPath: '/$lang/admin'
      preLoaderRoute: typeof LangAdminRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/api/public/verify-key': {
      id: '/api/public/verify-key'
      path: '/api/public/verify-key'
      fullPath: '/api/public/verify-key'
      preLoaderRoute: typeof ApiPublicVerifyKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deanonymize': {
      id: '/api/public/deanonymize'
      path: '/api/public/deanonymize'
      fullPath: '/api/public/deanonymize'
      preLoaderRoute: typeof ApiPublicDeanonymizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/anonymize': {
      id: '/api/public/anonymize'
      path: '/api/public/anonymize'
      fullPath: '/api/public/anonymize'
      preLoaderRoute: typeof ApiPublicAnonymizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LangRouteRouteChildren {
  LangAdminRoute: typeof LangAdminRoute
  LangAuthRoute: typeof LangAuthRoute
  LangContactRoute: typeof LangContactRoute
  LangDashboardRoute: typeof LangDashboardRoute
  LangEmailConfirmedRoute: typeof LangEmailConfirmedRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangTermsRoute: typeof LangTermsRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAdminRoute: LangAdminRoute,
  LangAuthRoute: LangAuthRoute,
  LangContactRoute: LangContactRoute,
  LangDashboardRoute: LangDashboardRoute,
  LangEmailConfirmedRoute: LangEmailConfirmedRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangTermsRoute: LangTermsRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  ApiPublicAnonymizeRoute: ApiPublicAnonymizeRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicDeanonymizeRoute: ApiPublicDeanonymizeRoute,
  ApiPublicVerifyKeyRoute: ApiPublicVerifyKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
